### ISSUE TITLE
Why did you choose Hapi instead of Express

### ISSUE THREAD

**Issue by anhcao142** [evilpacket/express-secure-skeleton#8]

**Comment by evilpacket** [comment]
My main like is it's built in input validation, most security issues stem from invalid user input and this pattern is something I've always enjoyed being a default. Sure you can add it to express, just historically auditing apps we've found that most express apps lack strong input validation and hapi apps have it, make your own conclusion there.


This is probably a good post to talk through some of the points. 

http://blog.npmjs.org/post/88024339405/nearing-practical-maintainability <http://blog.npmjs.org/post/88024339405/nearing-practical-maintainability>

The reality is both are good frameworks and use whatever you like for your reasons.

**Comment by anhcao142** [comment]
That's great, actually It's also a pain to me when dealing with input validation in Express. Maybe I will  give Hapi a try since I have been developed web apps with Express a lot and want to try something new.

Thank you for your insight 👍
